// panel/frontend/src/views/Account.vue
<template>
  <main id="content" class="min-h-screen pb-20 p-4 sm:p-8">
    <div v-if="userData" class="max-w-7xl mx-auto space-y-8">
       <!-- Account Settings Card -->
       <div class="glass p-6 sm:p-8 space-y-8">
          <div class="flex items-center justify-between border-b border-white/5 pb-4">
             <div class="flex items-center gap-3">
                <h2 class="text-xl font-bold text-white">Update Account</h2>
                <span class="px-2.5 py-0.5 rounded-full text-xs font-medium bg-neutral-600/30 text-neutral-400 border border-white/5">
                   {{ userData.username }}
                </span>
             </div>
             <span v-if="userData.twoFAEnabled" class="px-3 py-1 rounded-full text-xs font-medium bg-emerald-500/10 text-emerald-400 border border-emerald-500/20">
                2FA Enabled
             </span>
          </div>

          <!-- Username Update -->
          <div class="space-y-4">
             <h3 class="text-sm font-bold text-neutral-500 uppercase tracking-widest">Profile Information</h3>
             <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div>
                   <label class="block text-sm font-medium text-neutral-300 mb-1">Username</label>
                   <input v-model="newUsername" type="text" class="w-full" :placeholder="userData.username">
                </div>
                <div>
                   <label class="block text-sm font-medium text-neutral-300 mb-1">Email (Locked)</label>
                   <input :value="userData.email" type="email" disabled class="w-full opacity-50 cursor-not-allowed">
                </div>
             </div>
             <button @click="updateUsername" :disabled="!newUsername || newUsername === userData.username" class="bg-white text-black px-6 py-2 rounded-lg font-bold disabled:opacity-50">
                Update Username
             </button>
          </div>

          <!-- Password Update -->
          <div class="pt-8 border-t border-white/5 space-y-4">
             <h3 class="text-sm font-bold text-neutral-500 uppercase tracking-widest">Security</h3>
             <div class="space-y-4 max-w-md">
                <div>
                   <label class="block text-sm font-medium text-neutral-300 mb-1">Current Password</label>
                   <input v-model="currentPassword" type="password" class="w-full">
                </div>
                <div>
                   <label class="block text-sm font-medium text-neutral-300 mb-1">New Password</label>
                   <input v-model="newPassword" type="password" class="w-full">
                </div>
             </div>
             <button @click="updatePassword" :disabled="!currentPassword || !newPassword" class="bg-white text-black px-6 py-2 rounded-lg font-bold disabled:opacity-50">
                Update Password
             </button>
          </div>
       </div>
    </div>
  </main>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import api from '../services/api'

const userData = ref<any>(null)
const newUsername = ref('')
const currentPassword = ref('')
const newPassword = ref('')

onMounted(async () => {
  try {
    const res = await api.get('/account', { headers: { Accept: 'application/json' } })
    // In our refactored backend, /account returns { users }.
    // We actually need the current user, but App.vue already has it.
    // For this view, we'll fetch the specific details.
    const me = await api.get('/me')
    userData.value = me.data.user
  } catch (e) {
    console.error(e)
  }
})

async function updateUsername() {
  try {
    await api.post('/update-username', { currentUsername: userData.value.username, newUsername: newUsername.value })
    alert('Username updated. Logging out...')
    window.location.href = '/login'
  } catch (e: any) {
    alert(e.response?.data || 'Failed to update username')
  }
}

async function updatePassword() {
  try {
    await api.post('/change-password', { currentPassword: currentPassword.value, newPassword: newPassword.value })
    alert('Password updated. Logging out...')
    window.location.href = '/login'
  } catch (e: any) {
    alert(e.response?.data || 'Failed to update password')
  }
}
</script>

// panel-v3/frontend/src/app/account/page.tsx
"use client";

import React, { useState } from 'react';
import { User, Mail, Lock, Save, Camera } from 'lucide-react';

export default function AccountPage() {
  const [profile, setProfile] = useState({
    displayName: '',
    username: '',
    email: '',
  });

  const [loading, setLoading] = useState(true);

  React.useEffect(() => {
    fetch('/api/me')
      .then(res => res.json())
      .then(data => {
        setProfile({
          displayName: data.display_name || '',
          username: data.username || '',
          email: data.email || '',
        });
        setLoading(false);
      });
  }, []);

  const [passwords, setPasswords] = useState({
    current: '',
    new: '',
    confirm: ''
  });

  return (
    <div className="max-w-4xl mx-auto space-y-8">
      <div>
        <h1 className="text-3xl font-bold">Account Settings</h1>
        <p className="text-white/50">Manage your profile and security credentials</p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        <div className="lg:col-span-1">
          <div className="glass-dark p-8 rounded-2xl border border-white/5 text-center space-y-4">
            <div className="relative w-32 h-32 mx-auto">
              <div className="w-full h-full rounded-full bg-neon-blue/10 border-2 border-neon-blue/20 flex items-center justify-center overflow-hidden">
                <User className="w-16 h-16 text-neon-blue" />
              </div>
              <button className="absolute bottom-0 right-0 p-2 bg-neon-blue rounded-full shadow-neon text-black hover:scale-110 transition-transform">
                <Camera className="w-4 h-4" />
              </button>
            </div>
            <div>
              <h2 className="text-xl font-bold">{profile.displayName}</h2>
              <p className="text-sm text-white/40">@{profile.username}</p>
            </div>
            <div className="pt-4 border-t border-white/5">
              <p className="text-xs font-bold text-neon-blue uppercase tracking-widest">Administrator</p>
            </div>
          </div>
        </div>

        <div className="lg:col-span-2 space-y-8">
          <div className="glass-dark p-8 rounded-2xl border border-white/5 space-y-6">
            <h3 className="text-xl font-bold flex items-center gap-2">
              <User className="w-5 h-5 text-neon-blue" /> Profile Information
            </h3>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div className="space-y-1">
                <label className="text-xs font-bold text-white/40 uppercase ml-1">Display Name</label>
                <input
                  type="text"
                  className="w-full neon-input"
                  value={profile.displayName}
                  onChange={e => setProfile(p => ({ ...p, displayName: e.target.value }))}
                />
              </div>
              <div className="space-y-1">
                <label className="text-xs font-bold text-white/40 uppercase ml-1">Username</label>
                <input
                  type="text"
                  className="w-full neon-input"
                  value={profile.username}
                  onChange={e => setProfile(p => ({ ...p, username: e.target.value }))}
                />
              </div>
            </div>

            <div className="space-y-1 opacity-60">
              <label className="text-xs font-bold text-white/40 uppercase ml-1">Email Address (Locked)</label>
              <div className="relative">
                <Mail className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-white/30" />
                <input
                  type="email"
                  className="w-full neon-input pl-10 cursor-not-allowed"
                  value={profile.email}
                  readOnly
                />
              </div>
            </div>

            <div className="pt-4">
              <button
                onClick={async () => {
                  const res = await fetch('/api/users', {
                    method: 'PUT',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify(profile)
                  });
                  if (res.ok) alert('Profile updated');
                }}
                className="neon-button flex items-center gap-2 px-6"
              >
                <Save className="w-4 h-4" /> Save Changes
              </button>
            </div>
          </div>

          <div className="glass-dark p-8 rounded-2xl border border-white/5 space-y-6">
            <h3 className="text-xl font-bold flex items-center gap-2">
              <Lock className="w-5 h-5 text-neon-blue" /> Change Password
            </h3>

            <div className="space-y-4">
              <div className="space-y-1">
                <label className="text-xs font-bold text-white/40 uppercase ml-1">Current Password</label>
                <input
                  type="password"
                  className="w-full neon-input"
                  placeholder="••••••••"
                  value={passwords.current}
                  onChange={e => setPasswords(p => ({ ...p, current: e.target.value }))}
                />
              </div>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div className="space-y-1">
                  <label className="text-xs font-bold text-white/40 uppercase ml-1">New Password</label>
                  <input
                    type="password"
                    className="w-full neon-input"
                    placeholder="••••••••"
                    value={passwords.new}
                    onChange={e => setPasswords(p => ({ ...p, new: e.target.value }))}
                  />
                </div>
                <div className="space-y-1">
                  <label className="text-xs font-bold text-white/40 uppercase ml-1">Confirm New Password</label>
                  <input
                    type="password"
                    className="w-full neon-input"
                    placeholder="••••••••"
                    value={passwords.confirm}
                    onChange={e => setPasswords(p => ({ ...p, confirm: e.target.value }))}
                  />
                </div>
              </div>
            </div>

            <div className="pt-4">
              <button
                onClick={async () => {
                  if (passwords.new !== passwords.confirm) {
                    alert('New passwords do not match');
                    return;
                  }
                  const res = await fetch('/api/users', {
                    method: 'PUT',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({ ...profile, password: passwords.new })
                  });
                  if (res.ok) alert('Password updated');
                }}
                className="neon-button flex items-center gap-2 px-6"
              >
                <Save className="w-4 h-4" /> Update Password
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
